- onnxmltools/convert/common/ConvertContext.py
- onnxmltools/convert/common/NodeBuilder.py
- tests/common/test_ModelBuilder.py
- tests/common/test_NodeBuilder.py
- tests/coreml/test_coreml_convert.py
Currently, we have some special symbols in our variable/operator names but ONNX requires C-style. This PR fixes this problem. I know it's a bit dangerous to use "_" because CoreML uses it in their names frequently. This risk will be resolved by our new framework (#12 )
> Adopt C-style names

- onnxmltools/convert/common/_container.py
- onnxmltools/convert/common/_topology.py
- onnxmltools/convert/coreml/operator_converters/neural_network/BatchNorm.py
- onnxmltools/convert/coreml/operator_converters/neural_network/BidirectionalLSTM.py
- onnxmltools/convert/coreml/operator_converters/neural_network/Convolution.py
- onnxmltools/convert/coreml/operator_converters/neural_network/GRU.py
- onnxmltools/convert/coreml/operator_converters/neural_network/InnerProduct.py
- onnxmltools/convert/coreml/operator_converters/neural_network/LSTM.py
- onnxmltools/convert/coreml/operator_converters/neural_network/Pad.py
- onnxmltools/convert/coreml/operator_converters/neural_network/Pool.py
- onnxmltools/convert/coreml/operator_converters/neural_network/SimpleRNN.py
- onnxmltools/convert/coreml/shape_calculators/neural_network/Merge.py
- onnxmltools/convert/main.py
- onnxmltools/convert/sklearn/operator_converters/OneHotEncoder.py
Fixes
-Create RNN-induced nodes in a topological order
-Add initializers to graph input list
-Fix C-style name for Core ML's  convolution and fully-connected layer conversions
-Remove redundant attributes for InstanceNormalization, Pad, and one-hot encoder.
-Fix the shape calculator for merge layers (e.g., add, max)
> Fix some bugs found by running onnx-1.1.2 checker

- onnxmltools/convert/coreml/operator_converters/neural_network/Pool.py
Pool doesn't have dilation attribute now so we remove it. If you find a runtime still needs this attribute, please use WinMLTools.
> Remove unsupported attribute (onnx-1.1.2)

- onnxmltools/__init__.py
- onnxmltools/convert/keras/_parse.py
- onnxmltools/convert/keras/convert.py
- onnxmltools/convert/keras/operator_converters/BatchNorm.py
- onnxmltools/convert/keras/operator_converters/Dense.py
- onnxmltools/convert/main.py
- requirements-dev.txt
- tests/end2end/test_single_operator_with_cntk_backend.py
1. Add some basic end-to-end tests
2. Fix batch normalization and dense layer conversions
3. Remove redundant class in keras/_parser.py
4. Sync Keras conversion function interface with CoreML's and scikit-learn's
5. Fix keras==2.0.9 for CI tests
> Add Keras end-to-end tests

- onnxmltools/convert/keras/_parse.py
- requirements-dev.txt
Keras attribute "inboud_nodes" is changed to "_inbound_nodes," so our parser needs to be fixed accordingly. With this change, the latest Keras can be supported. This PR will close [this issue](https://github.com/onnx/onnxmltools/issues/37).
> Aware of recent Keras attribute name's change

- onnxmltools/convert/common/_apply_operation.py
- onnxmltools/convert/common/_topology.py
- onnxmltools/convert/coreml/operator_converters/neural_network/Embed.py
Previously, we were not able to get full funtionality of CoreML embedding layer because ONNX Gather needs interger input. After adding Cast right before ONNX, we should be good.
> A Better Support of CoreML Embedding (onnx-1.2)

- onnxmltools/convert/common/_topology.py
- onnxmltools/convert/coreml/_parse.py
- onnxmltools/convert/coreml/convert.py
- onnxmltools/convert/coreml/shape_calculators/Classifier.py
- onnxmltools/convert/coreml/shape_calculators/TensorToLabel.py
- onnxmltools/convert/coreml/shape_calculators/TensorToProbabilityMap.py
- onnxmltools/convert/keras/_parse.py
- onnxmltools/convert/keras/convert.py
- onnxmltools/convert/main.py
- onnxmltools/convert/sklearn/_parse.py
- onnxmltools/convert/sklearn/convert.py
- onnxmltools/convert/sklearn/shape_calculators/LinearClassifier.py
- onnxmltools/convert/sklearn/shape_calculators/SVM.py
In ONNX-1.2, ZipMap will produce a sequence of maps. This PR provides a preview of required changes in ONNXMLTools.
Major changes:
- targeted_onnx_version is added to Topology, Scope, and Operator
- Shape calculators related to ZipMap now check Operator's targeted_onnx_version and then produce proper output types. If ONNX < 1.2, Map is produced. Otherwise, we create Seq<Map>.
> Revise shape calculators for producing Sequence of Maps (onnx-1.2)

- onnxmltools/convert/common/_topology.py
- onnxmltools/convert/coreml/convert.py
- onnxmltools/convert/keras/convert.py
- onnxmltools/convert/sklearn/convert.py
The targeted onnx version now is extracted form the onnx package installed. It should resolve [this issue](https://github.com/onnx/onnxmltools/issues/48).
> Get default targeted version from installed onnx package

- onnxmltools/convert/coreml/operator_converters/neural_network/Pool.py
ONNX-1.2 upgrades AveragePool to version 7 to include an attribute. This attribute is not useful for conversion correctness so we only change the version numbers when creating pooling operators.
> Update Pool versions created in CoreML converter

- .gitignore
- tests/end2end/test_single_operator_with_cntk_backend.py
Some warnings like:
test_single_operator_with_cntk_backend.py:291: UserWarning: Update your Model call to the Keras 2 API: Model(outputs=Tensor("ba..., inputs=Tensor("in...).
> Clean up some keras 2 Model API warnings in the test.

- onnxmltools/convert/keras/operator_converters/Bidirectional.py
- onnxmltools/convert/keras/operator_converters/__init__.py
- onnxmltools/convert/keras/shape_calculators/Bidirectional.py
- onnxmltools/convert/keras/shape_calculators/__init__.py
As title. We support 4 major configurations where `return_sequence=True/False` and `merge_mode=None/'concat'`. Note that Bidirectional in Keras doesn't work with `return_state=True`.
Fix [issue 50](https://github.com/onnx/onnxmltools/issues/50).
> Add Keras Bidirectional with LSTM

- onnxmltools/convert/coreml/operator_converters/neural_network/InnerProduct.py
- tests/end2end/test_single_operator_with_cntk_backend.py
In CoreML, dense layer can take either [N, C] or [N, C, 1, 1] as its input. Thus, when feeding [N, C, 1, 1]-input into ONNX Gemm, we adjust its I/O shapes for a better conversion (Gemm only accepts 2-D tensors). Address [issue 78](https://github.com/onnx/onnxmltools/issues/78).
> Reshape I/O shapes for dense layer when converting CoreML models

- onnxmltools/convert/coreml/shape_calculators/Classifier.py
- onnxmltools/convert/coreml/shape_calculators/TensorToProbabilityMap.py
- onnxmltools/convert/sklearn/shape_calculators/LinearClassifier.py
- onnxmltools/convert/sklearn/shape_calculators/SVM.py
Scalar is tensor with shape=[] in ONNX rather than with shape=[1]. Fix issue [86](https://github.com/onnx/onnxmltools/issues/86).
> Fix scalar shapes when defining dictionary

- onnxmltools/convert/coreml/operator_converters/TreeEnsemble.py
- onnxmltools/convert/coreml/operator_converters/neural_network/InnerProduct.py
"n_targets" is missing when converting Core ML regression trees. Gemm has 3 versions, 1, 6, and 7 but the current code only consider 1. Fix issue [87](https://github.com/onnx/onnxmltools/issues/87) and issue [85](https://github.com/onnx/onnxmltools/issues/85).
> Fix a missing "n_targets" and Gemm version

- onnxmltools/convert/common/_apply_operation.py
- onnxmltools/convert/coreml/operator_converters/TensorToProbabilityMap.py
- onnxmltools/convert/coreml/shape_calculators/TensorToProbabilityMap.py
The first dimension is assumed to be the batch size, N.
The product of all other dimensions are the feature size, C.
For example, [N, C, H, W] will be reshaped to [N, CxHxW] before
calling ZipMap.
> Reshape input of ZipMap if it is not 2-D.

- onnxmltools/convert/coreml/operator_converters/neural_network/BidirectionalLSTM.py
Instead of using Y produced by ONNX LSTM, we should connect Y_h to the second Reshape for adjusting output shapes. Otherwise, the Reshape may fail because Y has extra batch dimension.
> Correctly connect ONNX LSTM Y_h to a Reshape

- onnxmltools/convert/coreml/shape_calculators/Classifier.py
- onnxmltools/convert/coreml/shape_calculators/Regressor.py
- onnxmltools/convert/sklearn/shape_calculators/SVM.py
For the tree ensemble classifier (and this is true for other classifiers as well), one of the outputs has shape {N}, but the converter uses {N,1}. This fails some ONNX engine shape verification.
> Update coreml converter classifier and regressor output shape.

- onnxmltools/convert/sklearn/_parse.py
- onnxmltools/convert/sklearn/operator_converters/Scaler.py
- onnxmltools/convert/sklearn/shape_calculators/Scaler.py
- tests/sklearn/test_ScalerConverter.py
This PR makes MinMaxScaler and MaxAbsScaler in scikit-learn convertible. They are tested offline because CNTK (our test backend) doesn't support Scaler.
> Add two common scalers in scikit-learn

- onnxmltools/convert/keras/operator_converters/Reshape.py
according to keras spec,  target_shape does not include the batch axis.
> Fix the keras reshape op conversion.

- onnxmltools/convert/common/_apply_operation.py
- onnxmltools/convert/common/_container.py
- Uses API from #157 to update common functions to check for opset number instead of ONNX version number (see [opset to version mapping](https://github.com/onnx/onnx/blob/master/docs/Versioning.md#released-versions))
> ONNX 1.3 version update (Opset 8) for common functions

- onnxmltools/convert/keras/_parse.py
- onnxmltools/convert/keras/convert.py
- onnxmltools/convert/keras/operator_converters/Conv.py
- onnxmltools/convert/keras/shape_calculators/Conv.py
- onnxmltools/convert/main.py
Adding the capability to set default_batch_size on convert_keras and convert_coreml calls. This is much easier than trying to use initialize_types to try and do the same thing. As asked in a previous issue, I have gone through the keras code and concluded that indeed for Keras, the first dimension is always the batch dimension. Therefore using the same logic for coreml which has the same location for the batch dimension should be okay. The clearest example of such is the following reference code for keras reference implementation for batch_flatten backend function:
def batch_flatten(x):
return np.reshape(x, (x.shape[0], -1))
> Plumb default_batch_size for convert_* to keras/coreml

- README.md
- added relevant links
- [to be edited/completed] explanation for opset versioning in ONNXMLTools conversion
- fixed various minor grammar and wording choices for readability
> Doc Update for Opset Versioning Explanation

- README.md
- tests/lightgbm/test_LightGbmTreeEnsembleConvertersPkl.py
* Replaced the badge under Windows with the status of the Windows Azure pipeline for the master branch (Both CI build badges on README pointed to the Linux Azure pipeline for the master branch)
* Recover Linux CI build by skipping LightGBM pkl test
* Add XGBoost converter to README
> Update README with Windows CI Badge, XGBoost converter

- onnxmltools/convert/coreml/operator_converters/neural_network/ImageScaler.py
As title. Tested locally by comparing old and new converted ONNX models.
> Decompose CoreML ImageScaler when ONNX ImageScaler is not there.

- tests/svmlib/test_SVMConverters.py
As title. PR fix pending on ONNX Runtime: https://github.com/Microsoft/onnxruntime/pull/101
> Recover Linux CI build by skipping flaky libSVM test

- onnxmltools/convert/coreml/operator_converters/neural_network/Multiply.py
Updating CoreML operator input name in multiply.py, as noticed in #295 for a LeakyReLU conversion.
> Fixing multiply, LeakyReLU in CoreML conversion (resolving #295)

- onnxutils/onnxconverter_common/onnx_ops.py
- Upsample operation is deprecated in ONNX opset 10 -- implemented through the Resize op instead
- Created apply_resize & documented accordingly
> [Opset 10] Deprecate Upsample, create Resize op

- onnxmltools/convert/lightgbm/_parse.py
- onnxmltools/convert/lightgbm/convert.py
- onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
- onnxmltools/utils/tests_helper.py
- onnxmltools/utils/utils_backend_onnxruntime.py
- tests/lightgbm/test_LightGbmTreeEnsembleConverters.py
For users who need to train a LightGBM model on huge datasets that do
not fit the memory, they often choose to train through the Booster API,
which supports two_round loading of huge datasets, or the command line,
which exports a model.txt file that can only be reconstructed to a
Booster. Currently the ONNX converter does not support either case.
Most of the converter work is about processing information from the
dumped model dictionary. Other information can also be inferred from
that information as well. Here we wrap the Booster information to
facilitate the conversion process.
> feat: add support for lightgbm.Booster

- .azure-pipelines/win32-CI-nightly.yml
- .azure-pipelines/win32-conda-CI.yml
Coremltools master has a bug in PR 563 which breaks our windows nightly build. Use tag 3.1 instead.
> Install coremltools 3.1 instead of master

- requirements-dev.txt
h2o 3.28.1.2 breaks the nightly build
> Ping h2o version==3.28.0.3 to fix nightly build

- onnxmltools/convert/coreml/operator_converters/neural_network/Pool.py
Addressing incorrect converter default for AvgPool and MaxPool in opset 10 and above.
https://github.com/onnx/onnx/blob/master/docs/Changelog.md#attributes-132
> CoreML - Ceiling_mode default for AvgPool and MaxPool

- .azure-pipelines/linux-CI-nightly.yml
- .azure-pipelines/linux-conda-CI.yml
coremltools 4.0 just gets released on pypi and breaks our linux nightly build, see
```python
import sklearn.tree as _tree
from . import _sklearn_util   
model_type = "classifier"
>   sklearn_class = _tree.DecisionTreeClassifier
E   NameError: name '_tree' is not defined
```
windows nightly build pin coremltools to 3.1 so it is fine. This change pin linux CI build to coremltools 3.1 too.
> Pin coremltools==3.1 for CI pipeline

- onnxmltools/convert/lightgbm/convert.py
- requirements-dev.txt
In the next release of Hummingbird we will deprecate the ability to pass input types to the converter. This PR makes sure that the the lightGBM converter will work with the new Hummingbird API.
> Fix for API changes in Hummingbird 0.1.0

- .azure-pipelines/linux-CI-nightly.yml
- .azure-pipelines/linux-conda-CI.yml
- .azure-pipelines/win32-CI-nightly.yml
- .azure-pipelines/win32-conda-CI.yml
- onnxmltools/__init__.py
- onnxmltools/convert/lightgbm/convert.py
- requirements.txt
hummingbird.ml (in lightgbm) converter uses pytorch export, but opset 13 not supported yet. Downgrade to 12 at this moment.
> Update to opset 13

- onnxmltools/convert/coreml/operator_converters/neural_network/Activation.py
This fixes issues #331 & #376, but there are potentially more issues in other activation functions
> Fix PReLU conversion from CoreML

- onnxmltools/convert/xgboost/operator_converters/XGBoost.py
- tests/xgboost/test_xgboost_converters.py
Fix for issue https://github.com/microsoft/onnxruntime/issues/5450.
> Fix the converter when parameter best_ntree_limit is used

- onnxmltools/convert/lightgbm/_parse.py
- onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
Closes #462 
I have already added support for `objective='poisson'`, but I believe this PR also allows to easily add support for `objective='tweedie'` and `objective='gamma'`.
Ultimately, it would be useful to have "EXPONENTIAL" as a supported value in `attrs['post_transform']`, such that we don't have to handle this special case here. However, that seems to involve quite some changes in `onxx`/`onnxruntime`. If anybody knows how to move these changes upstream, that would be very appreciated.
What this PR is still missing is tests. I have tested this locally, asserting that the predictions of the LightGMB model and the ONNX model are equivalent. I don't see an easy way to add this to your test suite, though. Some advice on this would be great.
> Allow to add custom post transform functions that are not supported by the ONNX spec yet

- onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
When trying to convert a LightGBM model that uses categorical variables with `onnxmltools` and then loading it back with `onnxruntime`, I was getting a strange error message:
`ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.`
This happened because the `attrs["node_values"]` property contained float and string values.
```
set([type(val) for val in attrs["node_values"]])
{<class 'str'>, <class 'float'>}
```
The reason for that is because if `tree_structure['threshold']` is a string, it is appended to `attrs['nodes_values']` twice - once as float and once as string.
I fixed it so that I only gets appended once and now it's working. 😄
> Don't append threshold twice

- onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
Hi!
In #463 I added a bug (sorry about that!) by [changing that output node of the container](https://github.com/onnx/onnxmltools/pull/463/files#diff-6bd8fd0d594bbe670b1e60cd0f196ef22f7ad9d54a8b60122e4352438789a9c9R420). This is a really bad idea and can lead to strange side effects where this node will remain a container output, even after adding more nodes that use it as input.
Generally I believe it's much safer to use the `container.add_node` function instead, which is what I'm doing in this PR.
> add node to container instead of changing output node of container

- onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
- tests/lightgbm/test_lightgbm_missing_values.py
Fixed a bug, where the ONNX model would take a different path through the tree compared to the LGBM regressor when `tree_structure["missing_type"] == 'None' and float(tree_structure['threshold']) < 0.0`.
> Fix missing type in lgbm regressor

- .azure-pipelines/linux-conda-CI.yml
- onnxmltools/__init__.py
- onnxmltools/convert/lightgbm/_parse.py
- onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
- tests/lightgbm/test_LightGbmTreeEnsembleConverters.py
Conversion speed up for lightgbm model. For a big model (~40000 trees), the conversion goes from 3 hours to 10 minutes for lightgbm. Fixes #482.
> Improves lightgbm conversion speed

- onnxmltools/convert/main.py
> Support parameter shape_override and other options for convert_tensorflow

- onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
- tests/lightgbm/test_objective_functions.py
This PR adds support to directly convert LGBM models that use the objective 'quantile'.
There is no real difference in handling the output of a quantile model versus a regression model, since the quantile model is just a regression tuned to output a certain quantile, therefore it can be handled the same.
> add support for quantile objective for LGBM models

- onnxmltools/convert/xgboost/_parse.py
- onnxmltools/convert/xgboost/operator_converters/XGBoost.py
- tests/hummingbirdml/test_LightGbmTreeEnsembleConverters_hummingbird.py
- tests/xgboost/test_xgboost_converters.py
Based on #506.
After being restored, the loaded booster is not exactly the same in memory. `best_ntree_limit` is not saved during `save_model`.
This PR enables `num_class` and `n_estimators` inference through `tree_info` instead of `best_ntree_limit`. 
`tree_info` is a required property for gbtree JSON schema https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html?highlight=tree_info#json-schema.
> Fix conversion of XGBoost model after being restored - Cont

- onnxmltools/convert/sparkml/operator_converters/onehot_encoder.py
- onnxmltools/convert/sparkml/ops_input_output.py
- requirements-dev.txt
- tests/sparkml/test_onehot_encoder.py
- tests/sparkml/test_pipeline.py
> fix: ONNX conversion for Spark OneHotEncoder model

- onnxmltools/convert/sparkml/operator_converters/vector_assembler.py
- requirements-dev.txt
- tests/sparkml/test_vector_assembler.py
> fix: Converter for SparkML VectorAssembler does not support vector inputs correctly

- onnxmltools/convert/sparkml/operator_converters/__init__.py
- onnxmltools/convert/sparkml/operator_converters/k_means.py
- onnxmltools/convert/sparkml/ops_input_output.py
- onnxmltools/convert/sparkml/ops_names.py
- tests/sparkml/test_k_means.py
> feat: add support for SparkML KMeansModel conversion

- onnxmltools/convert/sparkml/operator_converters/scaler.py
- tests/sparkml/test_scaler.py
Signed-off-by: Jason Wang <jasowang@microsoft.com>
> fix: SparkML StandardScaler conversion fails when withStd or withMean is set to true

- .azure-pipelines/linux-conda-CI.yml
- .azure-pipelines/win32-conda-CI.yml
- requirements-dev.txt
- tests/svmlib/test_SVMConverters.py
Signed-off-by: xiaowuhu <xiaowuhu@microsoft.com>
1. shorten the CI pipeline to reduce running time, removing onnx 1.7 and below, removing onnxruntime 1.6 and below, keep python 3.8 and above.
2. scipy 1.9.0 will break the pipeline due to some component are deprecated and removed, so stick to 1.8.0
3. scikit-learn 1.1.2 will break the pipeline due to same reason, so just stick to 1.1.0
> update CI pipeline files

- onnxmltools/convert/lightgbm/_parse.py
When using convert_lightgbm, with zipmap set to false, onnx checker complains about 'probabilities' tensor that does not have a shape and the converted model cannot be used with onnxruntime.
This commit adds correct shape for this case.
> convert_lightgbm: Add shape to FloatTensor probabilities

- onnxmltools/convert/sparkml/utils.py
The getTensorTypeFromSpark method fails for Spark 3.3.0+. This [PR](https://github.com/apache/spark/pull/34320) added "()" for  `pyspark.sql.types.DataType` string representation.
> fix: getTensorTypeFromSpark fails for Spark 3.3.0+

- .azure-pipelines/linux-conda-CI.yml
- .azure-pipelines/win32-conda-CI.yml
- onnxmltools/convert/lightgbm/_parse.py
- onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
- onnxmltools/utils/tests_helper.py
- onnxmltools/utils/utils_backend.py
- requirements-dev.txt
- tests/coreml/test_cml_DictVectorizerConverter.py
- tests/coreml/test_cml_GLMClassifierConverter.py
- tests/coreml/test_cml_SupportVectorClassifierConverter.py
- tests/coreml/test_cml_TreeEnsembleClassifierConverter.py
- tests/coreml/test_cml_TreeEnsembleRegressorConverterXGBoost.py
- tests/hummingbirdml/test_LightGbmTreeEnsembleConverters_hummingbird.py
- tests/lightgbm/test_LightGbmTreeEnsembleConverters.py
- tests/sparkml/sparkml_test_utils.py
- tests/svmlib/test_SVMConverters.py
> Support for lightgbm >= 4.0

- onnxmltools/convert/sparkml/utils.py
> Sparml converter: support type StringType and StringType()

- .azure-pipelines/linux-conda-CI.yml
- .azure-pipelines/win32-conda-CI.yml
Bump ONNX 1.14.1 in CI pipelines.
~Verify ONNX 1.14.1 rc2.~ Closes https://github.com/onnx/onnxmltools/issues/643.
> Bump ONNX 1.14.1 in CI pipelines

- onnxmltools/convert/xgboost/shape_calculators/Classifier.py
There's an issue on binarry classifier when passing a booster object.
WrappedBooster will set num_class to 1 as trees//ntrees == 1 https://github.com/casassg/onnxmltools/blob/e7a2ef088fb336800d34bffa628abac79f1ecc14/onnxmltools/convert/xgboost/_parse.py#L100
This makes it such that when we try to calculate the ncl for the classifier we end up setting an output of N, 1 vs N,2 which is what ONNX will actually calculate. These produce errors on logs in onnx runtime.
Given binary:logistic will always produce [N,2] changing the order in the if clause should remove the error.
I can add a test to repro but wanted to send PR first for feedback.
Also removed a double assignation which I'm not certain why it was there.
> Handle issue with binary classifier setting output to [N,1] vs [N,2]
