onnx/onnxmltools

README.md
onnx-coreml will have corresponding cross link to onnxmltools (https://github.com/onnx/onnx-coreml/pull/55)
=> Cross link with onnx-coreml

onnxmltools/proto/__init__.py
=> Check onnx version before importing its modules

onnxmltools/convert/README.md, onnxmltools/convert/common/_topology.py, onnxmltools/convert/coreml/_parse.py, onnxmltools/convert/coreml/convert.py, onnxmltools/convert/sklearn/_parse.py, onnxmltools/convert/sklearn/convert.py, tests/sklearn/test_BinarizerConverter.py, tests/sklearn/test_DictVectorizerConverter.py, tests/sklearn/test_GLMClassifierConverter.py, tests/sklearn/test_GLMRegressorConverter.py, tests/sklearn/test_ImputerConverter.py, tests/sklearn/test_LabelEncoderConverter.py, tests/sklearn/test_NormalizerConverter.py, tests/sklearn/test_OneHotEncoderConverter.py, tests/sklearn/test_SVMConverters.py, tests/sklearn/test_ScalerConverter.py, tests/sklearn/test_TreeEnsembleConverters.py, tests/sklearn/test_pipeline.py
=> Unify the ways to specify initial types for CoreML and scikit-learn

.travis.yml, onnxmltools/convert/coreml/operator_converters/neural_network/UnaryFunction.py, onnxmltools/proto/__init__.py
Fix an attribute for Core ML threshold conversion:
https://github.com/onnx/onnxmltools/issues/23
Fix build (stick with onnx release version instead of using the latest master branch):
https://github.com/onnx/onnxmltools/pull/19
=> Fix unary conversion and a building problem

tests/end2end/test_single_operator_with_cntk_backend.py
1. One Sequential with multiple ops.
2. One Model with a recursive structure
3. One Model with both of recursive and shared structure
=> Add tests based on Keras

onnxmltools/convert/common/_apply_operation.py, onnxmltools/convert/coreml/operator_converters/neural_network/Add.py, onnxmltools/convert/coreml/operator_converters/neural_network/Bias.py, onnxmltools/convert/coreml/operator_converters/neural_network/Embed.py, onnxmltools/convert/coreml/operator_converters/neural_network/Multiply.py, onnxmltools/convert/coreml/operator_converters/neural_network/Scale.py
Update CoreML converters following [the proposed broadcasting behavior](https://gist.github.com/KeDengMS/76337ca350aaa222318a3dda47a6839a). More Numpy examples can be found [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html). Related ONNX PRs are [this ](https://github.com/onnx/onnx/pull/902)and [this](https://github.com/onnx/onnx/pull/907).
=> Adopt new broadcasting behavior (i.e., broadcasting in numpy)

onnxmltools/convert/coreml/operator_converters/__init__.py, onnxmltools/convert/coreml/operator_converters/neural_network/__init__.py, onnxmltools/convert/coreml/shape_calculators/__init__.py, onnxmltools/convert/coreml/shape_calculators/neural_network/__init__.py, onnxmltools/convert/keras/operator_converters/__init__.py, onnxmltools/convert/keras/shape_calculators/__init__.py, onnxmltools/convert/sklearn/_parse.py, onnxmltools/convert/sklearn/operator_converters/SVD.py, onnxmltools/convert/sklearn/operator_converters/__init__.py, onnxmltools/convert/sklearn/shape_calculators/SVD.py, onnxmltools/convert/sklearn/shape_calculators/__init__.py, tests/end2end/__init__.py, tests/end2end/test_single_operator_with_cntk_backend.py, tests/end2end/test_sklearn_with_cntk_backend.py
[Truncated SVD](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html) is convertible now.
=> Add truncated SVD in scikit-learn and its test

onnxmltools/convert/common/_apply_operation.py, onnxmltools/convert/common/_topology.py, onnxmltools/convert/coreml/_parse.py, onnxmltools/convert/keras/_parse.py, onnxmltools/convert/main.py, onnxmltools/convert/sklearn/_parse.py
1. Remove all 1.1.2 strings
2. Use `onnx.__version__` as the default targeted version
3. Fix typo
4. Convert float + int list into pure float list for fixing Upsamle
This should address [this issue](https://github.com/onnx/onnxmltools/issues/55).
=> Fix multiple version problems

onnxmltools/convert/sklearn/_parse.py, onnxmltools/convert/sklearn/operator_converters/LinearRegressor.py, onnxmltools/convert/sklearn/shape_calculators/LinearRegressor.py, tests/sklearn/test_GLMRegressorConverter.py
Reuse code for linear regressor to convert elastic net.
=> Add elastic net regressor

onnxmltools/convert/common/_apply_operation.py
Attribute "is_test" got removed in ONNX-1.2 so we add a if-else
branch to handle it.
=> Update batch normalization's attrubute assignment

onnxmltools/convert/coreml/operator_converters/neural_network/BidirectionalLSTM.py, onnxmltools/convert/coreml/operator_converters/neural_network/GRU.py, onnxmltools/convert/coreml/operator_converters/neural_network/LSTM.py, onnxmltools/convert/coreml/operator_converters/neural_network/SimpleRNN.py, onnxmltools/convert/coreml/shape_calculators/neural_network/BidirectionalLSTM.py, onnxmltools/convert/keras/operator_converters/Bidirectional.py, onnxmltools/convert/keras/operator_converters/GRU.py, onnxmltools/convert/keras/operator_converters/LSTM.py, onnxmltools/convert/keras/operator_converters/SimpleRNN.py
As title. Fix [issue 69](https://github.com/onnx/onnxmltools/issues/69).
=> Update RNN conversion code to count multiple versions

README.md, README.rst, onnxmltools/convert/coreml/_parse.py, onnxmltools/convert/keras/_parse.py, onnxmltools/convert/sklearn/convert.py
Add some documents for Keras converters. Fix [issue 66](https://github.com/onnx/onnxmltools/issues/66) and [issue 68](https://github.com/onnx/onnxmltools/issues/68).
=> Update Keras- and scikit-learn-related documents

onnxmltools/convert/common/_apply_operation.py
There are three different PRelu versions, 1, 6, and 7. Add 6 back for ONNX-1.1.
=> Add PRelu version 6 if-else branch

onnxmltools/convert/README.md
=> Polish document

onnxmltools/convert/sklearn/convert.py
Explicitly show the place to find an example of initial_types. Address [issue 43](https://github.com/onnx/onnxmltools/issues/43).
=> Improve an error message

onnxmltools/convert/common/_apply_operation.py, onnxmltools/convert/coreml/_parse.py, onnxmltools/convert/coreml/operator_converters/neural_network/SequenceRepeat.py, onnxmltools/convert/coreml/shape_calculators/neural_network/Flatten.py, onnxmltools/convert/coreml/shape_calculators/neural_network/SequenceRepeat.py
1. CoreML dictionary values should be tensors with empty shape after
ONNX-1.2
2. Length of "repeat" in Tile should match input dimension
=> Fix two bugs

onnxmltools/convert/coreml/operator_converters/neural_network/Convolution.py, onnxmltools/convert/coreml/operator_converters/neural_network/Pool.py
Fix [issue 93](https://github.com/onnx/onnxmltools/issues/93).
=> Correct edge behavior of same padding

onnxmltools/convert/sklearn/shape_calculators/LinearClassifier.py, onnxmltools/convert/sklearn/shape_calculators/SVM.py
=> fix the classifier shape issues.

onnxmltools/utils/float16_converter.py
Add cast nodes for traditional ML ops
=> Float16 convert

onnxmltools/convert/common/_topology.py, onnxmltools/convert/common/case_insensitive_dict.py, onnxmltools/convert/common/data_types.py, onnxmltools/convert/common/utils.py, onnxmltools/convert/coreml/_parse.py, onnxmltools/convert/coreml/operator_converters/neural_network/ImageScaler.py, onnxmltools/utils/__init__.py, onnxmltools/utils/metadata_props.py, tests/coreml/test_AllNeuralNetworkConverters.py, tests/utils/test_utils.py
* Add functions to manipulate metadata props
* Add metadata props automatically if the input model has an image input
=> Manipulation of metadata props

onnxmltools/utils/float16_converter.py
The basic idea is removing for-loop and using numpy functions.
=> rewrite code to speed up raw_data conversion

onnxmltools/convert/common/utils.py, onnxmltools/convert/main.py
we need consume ketone package, so rename here after we did this for keras-onnx.
=> Rename ketone to keras2onnx

.azure-pipelines/win32-conda-CI.yml
- "install libsvm from github" is meant to be a comment
- minor formatting bug fix for pip install -r requirements-dev.txt line
=> LibSVM installation fix

onnxmltools/convert/common/_apply_operation.py, onnxmltools/convert/coreml/operator_converters/neural_network/Crop.py
Since ONNX Crop will be removed, let's be prepared for that.
=> Upgrade conversion of Core ML Crop

onnxmltools/convert/common/_apply_operation.py
* Sync changes made to common ONNX converter ops between with keras-onnx and onnxmltools [#31](https://github.com/onnx/keras-onnx/pull/31)
=> Sync _apply_operation.py changes from other converters

onnxmltools/convert/common/_apply_operation.py, onnxmltools/convert/coreml/operator_converters/neural_network/Activation.py, onnxmltools/convert/coreml/operator_converters/neural_network/Pool.py, onnxmltools/convert/coreml/operator_converters/neural_network/UnaryFunction.py
=> Decompose Affine when it no longer exists

onnxmltools/convert/common/_apply_operation.py, onnxmltools/convert/coreml/operator_converters/neural_network/Activation.py
As title. One step toward #259.
=> Decompose CoreML parametric softplus into ONNX operators

onnxmltools/convert/common/_apply_operation.py, onnxmltools/convert/coreml/operator_converters/neural_network/Activation.py
In preparation for experimental op deprecation in the next ONNX release (v1.5, opset 10). Last operator in #259.
=> Decompose ScaledTanh into ONNX operators

onnxmltools/convert/coreml/operator_converters/neural_network/Upsample.py, onnxutils/onnxconverter_common/onnx_ops.py
For consistency with other apply_ops and keras-onnx.
Brought up in https://github.com/onnx/keras-onnx/pull/62
=> Fix apply_upsample input in onnx_ops

requirements.txt
=> update requirements.txt with onnxconverter-common

onnxutils/README.md
As title. Minor wording update.
=> Update onnxconverter-common description

onnxutils/onnxconverter_common/__init__.py
=> Bump version for 1.4.1 onnxconverter-common release

onnxutils/onnxconverter_common/__init__.py, tests/svmlib/test_SVMConverters.py
- update package version for apply-slice bug fix release
- update tests for known svm runtime dimension error (#272, #280)
=> Update package version for onnxconverter-common

.azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-conda-CI.yml, README.md
As title. Added to both Linux and Windows CI builds in azure pipelines.
=> Add support for Py3.7, onnx 1.5, onnxruntime 0.4

onnxmltools/__init__.py, onnxmltools/convert/coreml/operator_converters/neural_network/Pool.py
Update AveragePool and MaxPool with ceil_mode attribute in CoreML conversion.
Fix minor typo and remove unnecessary init.py file comment.
=> [Opset 10] Pooling operator updates: AveragePool, MaxPool

onnxmltools/convert/coreml/operator_converters/neural_network/Activation.py, onnxutils/onnxconverter_common/onnx_ops.py
Adding apply_thresholded_relu, updating CoreML activation
=> [Opset 10] Update ThresholdedRelu

onnxutils/onnxconverter_common/__init__.py
Indicative of ONNX Version 10 support
=> Package version update for onnxconverter-common package

onnxmltools/__init__.py, requirements.txt, tests/svmlib/test_SVMConverters.py
prepare for new package publish, update onnxconverter-common requirement to 1.5.0
=> Updating onnxmltools package version and requirements to 1.5.0

onnxmltools/__init__.py
Fix for onnxmltools issue onnx#317
=> exposing  convert_xgboost API method

.azure-pipelines/linux-CI-nightly.yml, .azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-CI-nightly.yml, .azure-pipelines/win32-conda-CI.yml, onnxmltools/convert/coreml/_parse.py, onnxmltools/convert/libsvm/_parse.py, onnxmltools/convert/lightgbm/_parse.py, onnxmltools/convert/sparkml/_parse.py, onnxmltools/convert/xgboost/_parse.py, onnxmltools/utils/tests_helper.py, onnxmltools/utils/utils_backend_onnxruntime.py, tests/lightgbm/test_LightGbmTreeEnsembleConverters.py, tests/svmlib/test_SVMConverters.py, tests/xgboost/test_xgboost_converters.py, tests/xgboost/test_xgboost_unpickle_06.py
nightly build fails since 9/5/2019. This PR fixes it.
=> Set default_batch_size to 'None'

onnxmltools/convert/lightgbm/convert.py, requirements-dev.txt
=> Fix Hummingbird API changes

.azure-pipelines/linux-CI-nightly.yml, .azure-pipelines/win32-CI-nightly.yml
Signed-off-by: xavier dupré <xavier.dupre@gmail.com>
=> Fix torch import nightly build

README.md, onnxmltools/convert/sparkml/README.md
Signed-off-by: Jason Wang <jasowang@microsoft.com>
Reformatting the markdowns with markdownlint; fixing typos; updating known issue for OneHotEncoderModel.
=> docs: update sparkml doc; cleanups.

onnxmltools/convert/sparkml/operator_converters/string_indexer.py, onnxmltools/convert/sparkml/ops_input_output.py, tests/sparkml/test_string_indexer.py
Signed-off-by: Jason Wang <jasowang@microsoft.com>
=> feat: support inputCols and outputCols interfaces for converting Spark StringIndexerModel

onnxmltools/convert/sparkml/operator_converters/__init__.py, onnxmltools/convert/sparkml/operator_converters/mlp_classifier.py, onnxmltools/convert/sparkml/ops_input_output.py, tests/sparkml/test_mlp_classifier.py
Signed-off-by: Jason Wang <jasowang@microsoft.com>
=> feat: SparkML MultilayerPerceptronClassifier

.azure-pipelines/linux-conda-CI.yml, tests/sparkml/test_decision_tree_classifier.py
Signed-off-by: xadupre <xadupre@microsoft.com>
=> Add python 3.10 to CI

onnxmltools/convert/lightgbm/operator_converters/LightGbm.py
Signed-off-by: xadupre <xadupre@microsoft.com>
=> Fix mixed types when converting a LightGbm model

.azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-conda-CI.yml, onnxmltools/convert/sparkml/operator_converters/aft_survival_regression.py, onnxmltools/convert/sparkml/operator_converters/linear_regressor.py, onnxmltools/convert/xgboost/convert.py, onnxmltools/convert/xgboost/operator_converters/XGBoost.py, onnxmltools/proto/__init__.py, onnxmltools/utils/utils_backend_onnxruntime.py, tests/baseline/test_convert_baseline.py, tests/h2o/test_h2o_converters.py, tests/xgboost/test_xgboost_13.py, tests/xgboost/test_xgboost_converters.py, tests/xgboost/test_xgboost_pipeline.py
=> Update CI with latext onnxruntime, xgboost

onnxmltools/convert/sparkml/operator_converters/imputer.py, onnxmltools/convert/sparkml/ops_input_output.py, tests/sparkml/test_imputer.py
=> fix: Spark Imputer conversion with multiple input cols

.azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-conda-CI.yml, requirements-dev.txt
=> Check onnx==1.14

onnxmltools/convert/xgboost/operator_converters/XGBoost.py, tests/xgboost/test_xgboost_converters.py
=> Support count:poisson for XGBRegressor

.github/workflows/ci.yml, onnxmltools/proto/__init__.py
=> Remove import of split_complex_to_pairs and unused functions

onnxmltools/convert/xgboost/operator_converters/XGBoost.py
I took the liberty of helping to document the project and am looking into ways to improve it as well.
=> Add docstring for 2 classes and 1 function
